export const luxurylistings = [
    {
        id: 0,
        title: "Luxury 5 Bedroom Penthouse In A Secured Estate",
        location: "Victoria Island, Lagos",
        type: "Apartment",
        beds: 5,
        baths: 5,
        status: "For Sale",
        propertyID: 12345,
        rooms: 5,
        price: "#150,000,000",
        region: "Victoria Island",
        sqm: "500sqm",
        img: "/propImg1.jpg"
    },
    {
        id: 1,
        title: "Luxury 5 Bedroom Penthouse In A Secured Estate",
        location: "Victoria Island, Lagos",
        type: "Detached",
        beds: 5,
        baths: 5,
        status: "For Sale",
        propertyId: 12345,
        rooms: 5,
        price: "#150,000,000",
        region: "Victoria Island",
        sqm: "500sqm",
         img: "/propImg2.jpg"
    },
    {
        id: 2,
        title: "Luxury 5 Bedroom Penthouse In A Secured Estate",
        location: "Victoria Island, Lagos",
        type: "Apartment",
        beds: 5,
        baths: 5,
        status: "For Sale",
        propertyId: 12345,
        rooms: 5,
        price: "#150,000,000",
        region: "Victoria Island",
        sqm: "500sqm",
        img: "/propImg3.jpg"
    },
    {
        id: 3,
        title: "Luxury 5 Bedroom Penthouse In A Secured Estate",
        location: "Victoria Island, Lagos",
        type: "Apartment",
        beds: 5,
        baths: 5,
        status: "For Sale",
        propertyId: 12345,
        rooms: 5,
        price: "#150,000,000",
        region: "Victoria Island",
        sqm: "500sqm",
        img: "/propImg4.jpg"
    },{
        id: 4,
        title: "Luxury 5 Bedroom Penthouse In A Secured Estate",
        location: "Victoria Island, Lagos",
        type: "Detached",
        beds: 5,
        baths: 5,
        status: "For Sale",
        propertyId: 12345,
        rooms: 5,
        price: "#150,000,000",
        region: "Victoria Island",
        sqm: "500sqm",
        img: "/propImg1.jpg"
    },
    {
        id: 5,
        title: "Luxury 5 Bedroom Penthouse In A Secured Estate",
        location: "Victoria Island, Lagos",
        type: "Apartment",
        beds: 5,
        baths: 5,
        status: "For Sale",
        propertyId: 12345,
        rooms: 5,
        price: "#150,000,000",
        region: "Victoria Island",
        sqm: "500sqm",
        img: "/propImg1.jpg"
    },
]



export const ikoyilistings = [
    {
        id: 0,
        title: "Luxury 5 Bedroom Penthouse In A Secured Estate",
        location: "Victoria Island, Lagos",
        type: "Apartment",
        beds: 5,
        baths: 5,
        status: "For Sale",
        propertyID: 12345,
        rooms: 5,
        price: "#150,000,000",
        region: "Victoria Island",
        sqm: "500sqm",
        img: "/propImg1.jpg"
    },
    {
        id: 1,
        title: "Luxury 5 Bedroom Penthouse In A Secured Estate",
        location: "Victoria Island, Lagos",
        type: "Detached",
        beds: 5,
        baths: 5,
        status: "For Sale",
        propertyId: 12345,
        rooms: 5,
        price: "#150,000,000",
        region: "Victoria Island",
        sqm: "500sqm",
         img: "/propImg2.jpg"
    },
    {
        id: 2,
        title: "Luxury 5 Bedroom Penthouse In A Secured Estate",
        location: "Victoria Island, Lagos",
        type: "Detached",
        beds: 5,
        baths: 5,
        status: "For Sale",
        propertyId: 12345,
        rooms: 5,
        price: "#150,000,000",
        region: "Victoria Island",
        sqm: "500sqm",
        img: "/propImg3.jpg"
    },
    {
        id: 3,
        title: "Luxury 5 Bedroom Penthouse In A Secured Estate",
        location: "Victoria Island, Lagos",
        type: "Apartment",
        beds: 5,
        baths: 5,
        status: "For Sale",
        propertyId: 12345,
        rooms: 5,
        price: "#150,000,000",
        region: "Victoria Island",
        sqm: "500sqm",
        img: "/propImg4.jpg"
    },{
        id: 4,
        title: "Luxury 5 Bedroom Penthouse In A Secured Estate",
        location: "Victoria Island, Lagos",
        type: "Detached",
        beds: 5,
        baths: 5,
        status: "For Sale",
        propertyId: 12345,
        rooms: 5,
        price: "#150,000,000",
        region: "Victoria Island",
        sqm: "500sqm",
        img: "/propImg1.jpg"
    },
    {
        id: 5,
        title: "Luxury 5 Bedroom Penthouse In A Secured Estate",
        location: "Victoria Island, Lagos",
        type: "Detached",
        beds: 5,
        baths: 5,
        status: "For Sale",
        propertyId: 12345,
        rooms: 5,
        price: "#150,000,000",
        region: "Victoria Island",
        sqm: "500sqm",
        img: "/propImg1.jpg"
    },
]